name: Type-Check

on:
  workflow_call:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check PR

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm install --ignore-scripts

      - name: TypeScript Check
        run: npm run ts
