export enum TokenType {
  LEFT_PAREN = "LEFT_PAREN",
  RIGHT_PAREN = "RIGHT_PAREN",
  LEFT_BRACE = "LEFT_BRACE",
  RIGHT_BRACE = "RIGHT_BRACE",
  SEMICOLON = "SEMICOLON",
  IDENTIFIER = "IDENTIFIER",
  ELSE = "ELSE",
  FUNCTION = "FUNCTION",
  IF = "IF",
  WHILE = "WHILE",
  EOF = "EOF",
}
