name: Deploy

on:
  pull_request:
    types: ["closed"]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Check PR

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install --ignore-scripts

      - name: Deploy to GH-Pages
        run: npm run deploy -- -m "Deploy Jeka  to GitHub Pages"
